
#server:
#  port: 8010 # ?? ??(???? 8080) -> ?? ?? ??? ??? ??.
spring:
#  profiles:
#    active: dev # ????? dev ???? ?? @Profile??????? ????? ????
  thymeleaf:
    cache: false # ???? ?? ??
    prefix: file:src/main/resources/templates/ # ???? ?? ??(? ??? ?? ??)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basic1__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul # ??? ?? ??????
    username: kyj
    password: kyj1234567890
  jpa:
    hibernate:
      ddl-auto: update # DB ??? ????(??? ???? ??? ?) ???? ?? ??? ??? ???
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true